### ISSUE TITLE
core: some wallets should be unlocked when signing in

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#214]
There are some situations for which wallets should be unlocked while we have the encryption key during `Login`.

1. If there are DEX accounts that have their registration transaction broadcast but have not sent the `notifyfee`, presumably because the client was shut down while awaiting confirmations, then the DCR wallet should be unlocked when logging in.

2. If there are booked limit orders, the wallets involved should be unlocked. 

3. If there are matches in negotiation, the wallet(s) needed to complete negotiation should be unlocked.

**Comment by chappjc** [comment]
I hit 1. while testing, so I agree this makes sense.  Number 2 and 3 are especially true.  Related: https://github.com/decred/dcrdex/issues/237

**Comment by buck54321** [comment]
A different but maybe related issue: The user must individually unlock both wallets before placing an order. The two wallet unlocks and 1 order are three times in a row the app password must be entered. Instead, the `Trade` method should connect and unlock the wallets as necessary.

**Comment by buck54321** [comment]
Resolved by #316.

**Comment by itswisdomagain** [comment]
Looks like that PR only partially resolved this issue, the part about performing all required wallet unlocks in `core.Trade`.

The 3 scenarios in this issue description, that deal with unlocking wallets in `core.Login` are not resolved yet.

**Comment by buck54321** [comment]
3 is was resolved separately (see `dbTrackers`), but you're right that 2 is not completely resolved because if a booked limit order has no known matches, if will miss the loop logic in `dbTrackers`. That's a bug, I think. Reopening.

**Comment by buck54321** [comment]
Actually, looking again, I think all the bases are covered here. Closing again.

**Comment by itswisdomagain** [comment]
Looking again, you're right. This was resolved #267 though, not #316.
